[package]
name = "niri-zones"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
toml.workspace = true
zones-config = { path = "../zones-config" }
zones-core = { path = "../zones-core" }
zones-niri = { path = "../zones-niri" }
