[package]
name = "zones-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
regex.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
zones-core = { path = "../zones-core" }
